// ============================================================
//  data.js  –  English Coach (A1/A2) for Spanish speakers
//  nl  = English sentence the student must TYPE
//  en  = Spanish prompt shown to the student
// ============================================================

// ── helper functions for the verbs array ────────────────────
function r(inf, enTrans) {
  const stem = inf;
  let s3;
  if (inf.endsWith('s') || inf.endsWith('sh') || inf.endsWith('ch') || inf.endsWith('x') || inf.endsWith('o')) {
    s3 = inf + 'es';
  } else if (/[^aeiou]y$/.test(inf)) {
    s3 = inf.slice(0, -1) + 'ies';
  } else {
    s3 = inf + 's';
  }
  let pastBase;
  if (/[^aeiou]e$/.test(inf)) pastBase = inf + 'd';
  else if (/[^aeiou]y$/.test(inf)) pastBase = inf.slice(0, -1) + 'ied';
  else pastBase = inf + 'ed';
  return {
    inf: inf, meaning: enTrans, nl: inf, en: enTrans, level: 'A1',
    vtype: 'regular',
    present: [inf, inf, s3, inf, inf, inf],
    past: [pastBase, pastBase],
    participle: pastBase,
    auxiliary: 'have'
  };
}
function ii(inf, enTrans, present6, past, pastpl, participle, aux) {
  return {
    inf: inf, meaning: enTrans, nl: inf, en: enTrans, level: 'A1',
    vtype: 'irregular',
    present: present6,
    past: [past, pastpl],
    participle,
    auxiliary: aux || 'have'
  };
}

// ════════════════════════════════════════════════════════════
//  1. defaultSentences
//  nl = English (what the student types)
//  en = Spanish (the prompt shown)
// ════════════════════════════════════════════════════════════
const defaultSentences = [

  // ── Saludos e introducciones ─────────────────────────────
  { nl: 'What is your name?',
    en: '¿Cómo te llamas?',
    level: 'A1', unit: 1, stype: 'Question',
    srule: 'What + is + your + noun — pregunta con "what" al inicio' },

  { nl: 'My name is Ana.',
    en: 'Me llamo Ana.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'My + noun + is + nombre — sujeto + verbo + complemento' },

  { nl: 'How old are you?',
    en: '¿Cuántos años tienes?',
    level: 'A1', unit: 1, stype: 'Question',
    srule: 'How old + are + you — pregunta sobre la edad con "how old"' },

  { nl: 'I am twenty years old.',
    en: 'Tengo veinte años.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'I + am + número + years old — en inglés se usa "be" para la edad' },

  { nl: 'Where are you from?',
    en: '¿De dónde eres?',
    level: 'A1', unit: 1, stype: 'Question',
    srule: 'Where + are + you + from — pregunta de origen, preposición al final' },

  { nl: 'I am from Spain.',
    en: 'Soy de España.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'I + am + from + lugar — sujeto + verbo "be" + complemento' },

  { nl: 'Good morning.',
    en: 'Buenos días.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'Expresión fija de saludo según la hora del día' },

  { nl: 'Good night.',
    en: 'Buenas noches.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'Expresión fija de despedida nocturna' },

  { nl: 'Nice to meet you.',
    en: 'Mucho gusto.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'Expresión fija al conocer a alguien' },

  { nl: 'How are you?',
    en: '¿Cómo estás?',
    level: 'A1', unit: 1, stype: 'Question',
    srule: 'How + are + you — pregunta sobre el estado con "be"' },

  { nl: 'I am fine, thank you.',
    en: 'Estoy bien, gracias.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'I + am + adjetivo — sujeto + "be" + adjetivo de estado' },

  { nl: 'Goodbye.',
    en: 'Hasta luego.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'Expresión fija de despedida' },

  { nl: 'She is my sister.',
    en: 'Ella es mi hermana.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'She + is + my + noun — pronombre sujeto + "be" + posesivo + sustantivo' },

  { nl: 'He is my brother.',
    en: 'Él es mi hermano.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'He + is + my + noun — pronombre sujeto + "be" + posesivo + sustantivo' },

  { nl: 'They are my parents.',
    en: 'Ellos son mis padres.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'They + are + my + noun — pronombre plural + "are" + posesivo + sustantivo' },

  { nl: 'We are friends.',
    en: 'Somos amigos.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'We + are + noun — pronombre "we" + "are" + sustantivo' },

  { nl: 'I am happy.',
    en: 'Estoy contento/a.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'I + am + adjetivo — "be" para describir estados o emociones' },

  { nl: 'She is a teacher.',
    en: 'Ella es profesora.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'She + is + a + profesión — en inglés siempre se usa artículo con profesiones' },

  { nl: 'Is he your father?',
    en: '¿Es él tu padre?',
    level: 'A1', unit: 1, stype: 'Question',
    srule: 'Is + he + your + noun — pregunta con "be" invirtiendo sujeto y verbo' },

  { nl: 'Are you a student?',
    en: '¿Eres estudiante?',
    level: 'A1', unit: 1, stype: 'Question',
    srule: 'Are + you + a + noun — pregunta con "be" + artículo + profesión/rol' },

  { nl: 'I am not tired.',
    en: 'No estoy cansado/a.',
    level: 'A1', unit: 1, stype: 'Negation',
    srule: 'I + am + not + adjetivo — negación de "be" en 1ª persona' },

  { nl: 'She is not here.',
    en: 'Ella no está aquí.',
    level: 'A1', unit: 1, stype: 'Negation',
    srule: 'She + is + not + adverbio — negación de "be" en 3ª persona' },

  { nl: 'It is cold today.',
    en: 'Hace frío hoy.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'It + is + adjetivo — sujeto impersonal "it" para el tiempo atmosférico' },

  { nl: 'My telephone number is five, three, two, one.',
    en: 'Mi número de teléfono es cinco, tres, dos, uno.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'My + noun + is + números — usar "be" para dar información personal' },

  { nl: 'I have two brothers.',
    en: 'Tengo dos hermanos.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'I + have + número + noun — verbo "have" para posesión familiar' },

  { nl: 'There are five people in my family.',
    en: 'Hay cinco personas en mi familia.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'There + are + número + noun — "there are" para describir cantidad' },

  { nl: 'Good afternoon.',
    en: 'Buenas tardes.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'Expresión fija de saludo por la tarde' },

  { nl: 'See you tomorrow.',
    en: 'Nos vemos mañana.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'Expresión fija de despedida informal' },

  { nl: 'I am from Mexico.',
    en: 'Soy de México.',
    level: 'A1', unit: 1, stype: 'Statement',
    srule: 'I + am + from + país — "be from" para indicar el origen' },

  // ── Familia ──────────────────────────────────────────────
  { nl: 'This is my mother.',
    en: 'Esta es mi madre.',
    level: 'A1', unit: 2, stype: 'Statement',
    srule: 'This + is + my + noun — presentación con demostrativo "this"' },

  { nl: 'My father works in an office.',
    en: 'Mi padre trabaja en una oficina.',
    level: 'A1', unit: 2, stype: 'Statement',
    srule: 'Sujeto + verbo 3ª persona (-s) + complemento' },

  { nl: 'I have a sister and a brother.',
    en: 'Tengo una hermana y un hermano.',
    level: 'A1', unit: 2, stype: 'Statement',
    srule: 'I + have + artículo + noun — verbo "have" para posesión' },

  { nl: 'Do you have children?',
    en: '¿Tienes hijos?',
    level: 'A1', unit: 2, stype: 'Question',
    srule: 'Do + you + verbo base — auxiliar "do" para preguntas en presente simple',
    gtopic: 'question' },

  { nl: 'My grandmother lives with us.',
    en: 'Mi abuela vive con nosotros.',
    level: 'A1', unit: 2, stype: 'Statement',
    srule: 'Sujeto + verbo 3ª persona + preposición + pronombre objeto' },

  { nl: 'My son is three years old.',
    en: 'Mi hijo tiene tres años.',
    level: 'A1', unit: 2, stype: 'Statement',
    srule: 'En inglés la edad usa "be": sujeto + is + número + years old' },

  { nl: 'She is my best friend.',
    en: 'Ella es mi mejor amiga.',
    level: 'A1', unit: 2, stype: 'Statement',
    srule: 'She + is + my + adjetivo + noun — pronombre sujeto + "be" + sintagma nominal' },

  { nl: 'Where does your family live?',
    en: '¿Dónde vive tu familia?',
    level: 'A1', unit: 2, stype: 'Question',
    srule: 'Where + does + sujeto + verbo base — auxiliar "does" en 3ª persona',
    gtopic: 'question' },

  { nl: 'My husband is a doctor.',
    en: 'Mi marido es médico.',
    level: 'A1', unit: 2, stype: 'Statement',
    srule: 'Sujeto + is + artículo + profesión — artículo indeterminado con profesiones' },

  { nl: 'We have a baby.',
    en: 'Tenemos un bebé.',
    level: 'A1', unit: 2, stype: 'Statement',
    srule: 'We + have + artículo + noun — plural "we" con "have"' },

  { nl: 'My brother studies every morning.',
    en: 'Mi hermano estudia todas las mañanas.',
    level: 'A1', unit: 2, stype: 'Statement',
    srule: 'My + family + verbo 3ª persona + time — presente simple para rutinas' },

  { nl: 'She works on Monday and Tuesday.',
    en: 'Ella trabaja el lunes y el martes.',
    level: 'A1', unit: 2, stype: 'Statement',
    srule: 'She + verbo 3ª persona + on + days — preposición "on" con días de la semana' },

  { nl: 'My grandmother is a good woman.',
    en: 'Mi abuela es una buena mujer.',
    level: 'A1', unit: 2, stype: 'Statement',
    srule: 'My + family + is + artículo + adjetivo + noun — "be" con adjetivo descriptivo' },

  { nl: 'My daughter likes the new house.',
    en: 'A mi hija le gusta la casa nueva.',
    level: 'A1', unit: 2, stype: 'Statement',
    srule: 'My + family + likes + artículo + adjetivo + noun — like con complemento' },

  { nl: 'We have dinner in the evening.',
    en: 'Cenamos por la noche.',
    level: 'A1', unit: 2, stype: 'Statement',
    srule: 'We + have + noun + in the evening — "have" para comidas + expresión de tiempo' },

  // ── Colores y ropa ───────────────────────────────────────
  { nl: 'My shirt is red.',
    en: 'Mi camiseta es roja.',
    level: 'A1', unit: 3, stype: 'Statement',
    srule: 'Sujeto + is + adjetivo de color — el adjetivo va después del verbo "be"' },

  { nl: 'She is wearing a blue dress.',
    en: 'Lleva un vestido azul.',
    level: 'A1', unit: 3, stype: 'Statement',
    srule: 'She + is + wearing + artículo + adjetivo + noun — presente continuo para ropa',
    gtopic: 'tenses' },

  { nl: 'What colour is your bag?',
    en: '¿De qué color es tu bolso?',
    level: 'A1', unit: 3, stype: 'Question',
    srule: 'What colour + is + sujeto — pregunta sobre color',
    gtopic: 'question' },

  { nl: 'I like the black shoes.',
    en: 'Me gustan los zapatos negros.',
    level: 'A1', unit: 3, stype: 'Statement',
    srule: 'I + like + artículo + adjetivo + noun plural — "like" con artículo determinado' },

  { nl: 'Do you have a green jacket?',
    en: '¿Tienes un abrigo verde?',
    level: 'A1', unit: 3, stype: 'Question',
    srule: 'Do + you + have + artículo + adjetivo + noun — pregunta de posesión',
    gtopic: 'question' },

  { nl: 'My socks are white.',
    en: 'Mis calcetines son blancos.',
    level: 'A1', unit: 3, stype: 'Statement',
    srule: 'My + noun plural + are + adjetivo — "be" en plural: "are"' },

  { nl: 'I want to buy some jeans.',
    en: 'Quiero comprar unos vaqueros.',
    level: 'A1', unit: 3, stype: 'Statement',
    srule: 'I + want + to + verbo base + some + noun — estructura "want to + infinitivo"' },

  { nl: 'That hat is very nice.',
    en: 'Ese sombrero es muy bonito.',
    level: 'A1', unit: 3, stype: 'Statement',
    srule: 'That + noun + is + adverb + adjetivo — demostrativo + "be" + adjetivo' },

  // ── Comida y bebida ──────────────────────────────────────
  { nl: 'I like coffee.',
    en: 'Me gusta el café.',
    level: 'A1', unit: 3, stype: 'Statement',
    srule: 'I + like + noun — gustar se traduce como "like" en inglés' },

  { nl: 'What do you want to eat?',
    en: '¿Qué quieres comer?',
    level: 'A1', unit: 3, stype: 'Question',
    srule: 'What + do + you + want + to + verbo base — pregunta de objeto con "what"',
    gtopic: 'question' },

  { nl: 'I want a glass of water, please.',
    en: 'Quiero un vaso de agua, por favor.',
    level: 'A1', unit: 3, stype: 'Statement',
    srule: 'I + want + artículo + noun + of + noun — expresión de cantidad con "of"' },

  { nl: 'Breakfast is at eight o\'clock.',
    en: 'El desayuno es a las ocho.',
    level: 'A1', unit: 3, stype: 'Statement',
    srule: 'Noun + is + at + hora — preposición "at" con horas' },

  { nl: 'He does not eat meat.',
    en: 'Él no come carne.',
    level: 'A1', unit: 3, stype: 'Negation',
    srule: 'He + does not + verbo base — negación en 3ª persona: "does not"',
    gtopic: 'negation' },

  { nl: 'We like apples.',
    en: 'Nos gustan las manzanas.',
    level: 'A1', unit: 3, stype: 'Statement',
    srule: 'We + like + noun plural — sin artículo para gustos generales en plural' },

  { nl: 'Do you drink milk in the morning?',
    en: '¿Bebes leche por las mañanas?',
    level: 'A1', unit: 3, stype: 'Question',
    srule: 'Do + you + verbo base + noun + in the morning — pregunta de rutina',
    gtopic: 'question' },

  { nl: 'The rice is delicious.',
    en: 'El arroz está delicioso.',
    level: 'A1', unit: 3, stype: 'Statement',
    srule: 'The + noun + is + adjetivo — "be" para descripción' },

  { nl: 'She drinks tea every morning.',
    en: 'Ella bebe té todas las mañanas.',
    level: 'A1', unit: 3, stype: 'Statement',
    srule: 'She + verbo 3ª persona + noun + frecuencia — presente simple para hábitos' },

  { nl: 'I do not like sugar.',
    en: 'No me gusta el azúcar.',
    level: 'A1', unit: 3, stype: 'Negation',
    srule: 'I + do not + like + noun — negación con "do not" en 1ª persona',
    gtopic: 'negation' },

  // ── Tiempo y transporte ──────────────────────────────────
  { nl: 'What time is it?',
    en: '¿Qué hora es?',
    level: 'A1', unit: 4, stype: 'Question',
    srule: 'What time + is + it — pregunta sobre la hora, sujeto impersonal "it"',
    gtopic: 'question' },

  { nl: 'It is half past three.',
    en: 'Son las tres y media.',
    level: 'A1', unit: 4, stype: 'Statement',
    srule: 'It + is + expresión de hora — sujeto impersonal "it" para la hora' },

  { nl: 'The train leaves at nine.',
    en: 'El tren sale a las nueve.',
    level: 'A1', unit: 4, stype: 'Statement',
    srule: 'Sujeto + verbo 3ª persona + at + hora — horario con presente simple' },

  { nl: 'What time does the bus arrive?',
    en: '¿A qué hora llega el autobús?',
    level: 'A1', unit: 4, stype: 'Question',
    srule: 'What time + does + sujeto + verbo base — pregunta de hora con "does"',
    gtopic: 'question' },

  { nl: 'I go to work by bicycle.',
    en: 'Voy al trabajo en bicicleta.',
    level: 'A1', unit: 4, stype: 'Statement',
    srule: 'I + go + to + lugar + by + transporte — preposición "by" para medios de transporte' },

  { nl: 'The airport is far away.',
    en: 'El aeropuerto está lejos.',
    level: 'A1', unit: 4, stype: 'Statement',
    srule: 'The + noun + is + adverbio de lugar — ubicación con "be"' },

  { nl: 'Is there a taxi nearby?',
    en: '¿Hay un taxi cerca?',
    level: 'A1', unit: 4, stype: 'Question',
    srule: 'Is + there + artículo + noun — pregunta con "there is"',
    gtopic: 'there-is' },

  { nl: 'I need a return ticket.',
    en: 'Necesito un billete de ida y vuelta.',
    level: 'A1', unit: 4, stype: 'Statement',
    srule: 'I + need + artículo + adjetivo + noun — "need" para necesidades' },

  { nl: 'The plane arrives tomorrow morning.',
    en: 'El avión llega mañana por la mañana.',
    level: 'A1', unit: 4, stype: 'Statement',
    srule: 'Sujeto + verbo 3ª persona + expresión de tiempo — presente simple para itinerarios' },

  { nl: 'She goes to work by car.',
    en: 'Ella va al trabajo en coche.',
    level: 'A1', unit: 4, stype: 'Statement',
    srule: 'She + goes (3ª persona de "go") + to + lugar + by + transporte' },

  // ── Casa ─────────────────────────────────────────────────
  { nl: 'Where do you live?',
    en: '¿Dónde vives?',
    level: 'A1', unit: 4, stype: 'Question',
    srule: 'Where + do + you + verbo base — WH-question en presente simple',
    gtopic: 'question' },

  { nl: 'I live in a small apartment.',
    en: 'Vivo en un apartamento pequeño.',
    level: 'A1', unit: 4, stype: 'Statement',
    srule: 'I + live + in + artículo + adjetivo + noun — "in" para lugares habitados' },

  { nl: 'There are two bedrooms in my house.',
    en: 'Hay dos dormitorios en mi casa.',
    level: 'A1', unit: 4, stype: 'Statement',
    srule: 'There + are + número + noun plural + in — "there are" para existencia en plural',
    gtopic: 'there-is' },

  { nl: 'The kitchen is big.',
    en: 'La cocina es grande.',
    level: 'A1', unit: 4, stype: 'Statement',
    srule: 'The + noun + is + adjetivo — descripción con artículo determinado' },

  { nl: 'There is no garden in my building.',
    en: 'No hay jardín en mi edificio.',
    level: 'A1', unit: 4, stype: 'Negation',
    srule: 'There + is + no + noun — negación de "there is" con "no"',
    gtopic: 'there-is' },

  { nl: 'How many rooms does your house have?',
    en: '¿Cuántas habitaciones tiene tu casa?',
    level: 'A1', unit: 4, stype: 'Question',
    srule: 'How many + noun plural + does + sujeto + have — pregunta de cantidad',
    gtopic: 'question' },

  { nl: 'The table is in the kitchen.',
    en: 'La mesa está en la cocina.',
    level: 'A1', unit: 4, stype: 'Statement',
    srule: 'The + noun + is + in + artículo + noun — ubicación con "be" + "in"' },

  { nl: 'My bed is very comfortable.',
    en: 'Mi cama es muy cómoda.',
    level: 'A1', unit: 4, stype: 'Statement',
    srule: 'My + noun + is + very + adjetivo — intensificador "very" + adjetivo' },

  { nl: 'Is there a bathroom on the first floor?',
    en: '¿Hay un baño en el primer piso?',
    level: 'A1', unit: 4, stype: 'Question',
    srule: 'Is + there + artículo + noun + on + ordinal + floor — pregunta "there is"',
    gtopic: 'there-is' },

  { nl: 'The window is open.',
    en: 'La ventana está abierta.',
    level: 'A1', unit: 4, stype: 'Statement',
    srule: 'The + noun + is + adjetivo/participio — "be" para estado del objeto' },

  // ── Negación ─────────────────────────────────────────────
  { nl: 'I do not speak Chinese.',
    en: 'No hablo chino.',
    level: 'A1', unit: 3, stype: 'Negation',
    srule: 'I + do not + verbo base — negación presente simple 1ª persona',
    gtopic: 'negation' },

  { nl: 'She does not work on Sundays.',
    en: 'Ella no trabaja los domingos.',
    level: 'A1', unit: 3, stype: 'Negation',
    srule: 'She + does not + verbo base — "does not" en 3ª persona del singular',
    gtopic: 'negation' },

  { nl: 'They are not brothers.',
    en: 'No son hermanos.',
    level: 'A1', unit: 3, stype: 'Negation',
    srule: 'They + are + not + noun — negación de "be" con "not"',
    gtopic: 'negation' },

  { nl: 'I am not tired.',
    en: 'No estoy cansada.',
    level: 'A1', unit: 3, stype: 'Negation',
    srule: 'I + am + not + adjetivo — negación de "be" en 1ª persona',
    gtopic: 'negation' },

  { nl: 'He does not have a car.',
    en: 'Él no tiene coche.',
    level: 'A1', unit: 3, stype: 'Negation',
    srule: 'He + does not + verbo base + artículo + noun — negación con "does not"',
    gtopic: 'negation' },

  // ── Preguntas WH ─────────────────────────────────────────
  { nl: 'What do you do at the weekend?',
    en: '¿Qué haces los fines de semana?',
    level: 'A1', unit: 3, stype: 'Question',
    srule: 'What + do + you + do + expresión de tiempo — "what" para preguntar sobre acciones',
    gtopic: 'question' },

  { nl: 'Why do you study English?',
    en: '¿Por qué estudias inglés?',
    level: 'A1', unit: 3, stype: 'Question',
    srule: 'Why + do + you + verbo base — "why" para preguntar la razón',
    gtopic: 'question' },

  { nl: 'Who is that person?',
    en: '¿Quién es esa persona?',
    level: 'A1', unit: 3, stype: 'Question',
    srule: 'Who + is + demostrativo + noun — "who" para preguntar sobre personas',
    gtopic: 'question' },

  { nl: 'When does the class start?',
    en: '¿Cuándo empieza la clase?',
    level: 'A1', unit: 3, stype: 'Question',
    srule: 'When + does + sujeto + verbo base — "when" para preguntar sobre tiempo',
    gtopic: 'question' },

  { nl: 'What is your teacher\'s name?',
    en: '¿Cómo se llama tu profesor?',
    level: 'A1', unit: 3, stype: 'Question',
    srule: 'What + is + posesivo + noun — pregunta sobre nombre con posesivo sajón',
    gtopic: 'question' },

  { nl: 'I do not like the green jacket.',
    en: 'No me gusta la chaqueta verde.',
    level: 'A1', unit: 3, stype: 'Negation',
    srule: 'I + do not + like + artículo + adjetivo color + clothing — negación con ropa y color',
    gtopic: 'negation' },

  { nl: 'What colour are your shoes?',
    en: '¿De qué color son tus zapatos?',
    level: 'A1', unit: 3, stype: 'Question',
    srule: 'What colour + are + posesivo + clothing — pregunta sobre color de ropa',
    gtopic: 'question' },

  { nl: 'She does not eat chicken.',
    en: 'Ella no come pollo.',
    level: 'A1', unit: 3, stype: 'Negation',
    srule: 'She + does not + eat + food — negación con comida en 3ª persona',
    gtopic: 'negation' },

  { nl: 'Do you like the orange dress?',
    en: '¿Te gusta el vestido naranja?',
    level: 'A1', unit: 3, stype: 'Question',
    srule: 'Do + you + like + artículo + colour + clothing — pregunta con ropa y color',
    gtopic: 'question' },

  { nl: 'He does not drink milk.',
    en: 'Él no bebe leche.',
    level: 'A1', unit: 3, stype: 'Negation',
    srule: 'He + does not + drink + food — negación con bebida',
    gtopic: 'negation' },

  // ── Presente continuo ────────────────────────────────────
  { nl: 'I am working right now.',
    en: 'Ahora mismo estoy trabajando.',
    level: 'A1', unit: 5, stype: 'Statement',
    srule: 'I + am + verbo-ing + adverbio — presente continuo para acción en progreso',
    gtopic: 'tenses' },

  { nl: 'She is eating at the moment.',
    en: 'Ella está comiendo en este momento.',
    level: 'A1', unit: 5, stype: 'Statement',
    srule: 'She + is + verbo-ing + at the moment — "be" conjugado + verbo-ing',
    gtopic: 'tenses' },

  { nl: 'We are learning English.',
    en: 'Estamos aprendiendo inglés.',
    level: 'A1', unit: 5, stype: 'Statement',
    srule: 'We + are + verbo-ing + objeto — presente continuo en 1ª persona plural',
    gtopic: 'tenses' },

  { nl: 'What are you doing?',
    en: '¿Qué estás haciendo?',
    level: 'A1', unit: 5, stype: 'Question',
    srule: 'What + are + you + verbo-ing — pregunta en presente continuo',
    gtopic: 'tenses' },

  { nl: 'I am not listening to music now.',
    en: 'No estoy escuchando música ahora.',
    level: 'A1', unit: 5, stype: 'Negation',
    srule: 'I + am + not + verbo-ing — negación del presente continuo',
    gtopic: 'tenses' },

  { nl: 'I am washing my hands.',
    en: 'Me estoy lavando las manos.',
    level: 'A1', unit: 5, stype: 'Statement',
    srule: 'I + am + verbo-ing + my + body part — presente continuo con parte del cuerpo',
    gtopic: 'tenses' },

  { nl: 'She is touching her nose.',
    en: 'Ella se está tocando la nariz.',
    level: 'A1', unit: 5, stype: 'Statement',
    srule: 'She + is + verbo-ing + her + body part — presente continuo con parte del cuerpo',
    gtopic: 'tenses' },

  { nl: 'My head is hurting right now.',
    en: 'Me duele la cabeza ahora mismo.',
    level: 'A1', unit: 5, stype: 'Statement',
    srule: 'My + body part + is + verbo-ing — presente continuo para dolor físico',
    gtopic: 'tenses' },

  { nl: 'He is moving his arm slowly.',
    en: 'Él está moviendo el brazo lentamente.',
    level: 'A1', unit: 5, stype: 'Statement',
    srule: 'He + is + verbo-ing + his + body part + adverb — presente continuo con cuerpo',
    gtopic: 'tenses' },

  { nl: 'Are you feeling cold?',
    en: '¿Tienes frío?',
    level: 'A1', unit: 5, stype: 'Question',
    srule: 'Are + you + verbo-ing + adjetivo — pregunta en presente continuo con adjetivo',
    gtopic: 'tenses' },

  { nl: 'The small boy is running fast.',
    en: 'El niño pequeño está corriendo rápido.',
    level: 'A1', unit: 5, stype: 'Statement',
    srule: 'Sujeto + adjetivo + is + verbo-ing + adverb — presente continuo con adjetivo',
    gtopic: 'tenses' },

  { nl: 'I am not closing my eyes.',
    en: 'No estoy cerrando los ojos.',
    level: 'A1', unit: 5, stype: 'Negation',
    srule: 'I + am + not + verbo-ing + my + body part — negación con parte del cuerpo',
    gtopic: 'tenses' },

  { nl: 'She is reading a difficult book.',
    en: 'Ella está leyendo un libro difícil.',
    level: 'A1', unit: 5, stype: 'Statement',
    srule: 'She + is + verbo-ing + artículo + adjetivo + noun — presente continuo con adjetivo',
    gtopic: 'tenses' },

  { nl: 'Is he writing with his left hand?',
    en: '¿Está escribiendo con la mano izquierda?',
    level: 'A1', unit: 5, stype: 'Question',
    srule: 'Is + he + verbo-ing + with + his + body part — pregunta con parte del cuerpo',
    gtopic: 'tenses' },

  // ── There is / There are ─────────────────────────────────
  { nl: 'There is a supermarket on the corner.',
    en: 'Hay un supermercado en la esquina.',
    level: 'A1', unit: 4, stype: 'Statement',
    srule: 'There + is + artículo + noun + on the corner — "there is" para existencia singular',
    gtopic: 'there-is' },

  { nl: 'There are many students in the class.',
    en: 'Hay muchos estudiantes en la clase.',
    level: 'A1', unit: 4, stype: 'Statement',
    srule: 'There + are + many + noun plural — "there are" para existencia plural',
    gtopic: 'there-is' },

  { nl: 'There is no milk in the fridge.',
    en: 'No hay leche en la nevera.',
    level: 'A1', unit: 4, stype: 'Negation',
    srule: 'There + is + no + noun incontable — negación de existencia con incontable',
    gtopic: 'there-is' },

  { nl: 'Is there a pharmacy near here?',
    en: '¿Hay una farmacia cerca de aquí?',
    level: 'A1', unit: 4, stype: 'Question',
    srule: 'Is + there + artículo + noun + near here — pregunta de existencia',
    gtopic: 'there-is' },

  // ── A2 sentences ─────────────────────────────────────────
  { nl: 'I usually get up at seven in the morning.',
    en: 'Normalmente me levanto a las siete de la mañana.',
    level: 'A2', unit: 2, stype: 'Statement',
    srule: 'Adverbio de frecuencia + sujeto + verbo + hora — "usually" antes del verbo' },

  { nl: 'Yesterday I went to the supermarket.',
    en: 'Ayer fui al supermercado.',
    level: 'A2', unit: 6, stype: 'Statement',
    srule: 'Yesterday + sujeto + verbo pasado — pasado simple con marcador temporal' },

  { nl: 'She is studying for the exam.',
    en: 'Ella está estudiando para el examen.',
    level: 'A2', unit: 5, stype: 'Statement',
    srule: 'She + is + verbo-ing + for + noun — presente continuo con propósito',
    gtopic: 'tenses' },

  { nl: 'My eyes are getting tired now.',
    en: 'Mis ojos se están cansando ahora.',
    level: 'A2', unit: 5, stype: 'Statement',
    srule: 'My + body part + are + getting + adjetivo — presente continuo con cuerpo y adjetivo',
    gtopic: 'tenses' },

  { nl: 'He is not moving his leg.',
    en: 'Él no está moviendo la pierna.',
    level: 'A2', unit: 5, stype: 'Negation',
    srule: 'He + is + not + verbo-ing + his + body part — negación del presente continuo con cuerpo',
    gtopic: 'tenses' },

  { nl: 'Are you feeling better now?',
    en: '¿Te sientes mejor ahora?',
    level: 'A2', unit: 5, stype: 'Question',
    srule: 'Are + you + feeling + adjetivo comparativo + now — pregunta en continuo con adjetivo',
    gtopic: 'tenses' },

  { nl: 'Have you ever been to London?',
    en: '¿Has estado alguna vez en Londres?',
    level: 'A2', unit: 6, stype: 'Question',
    srule: 'Have + you + ever + participio — presente perfecto con "ever" para experiencias',
    gtopic: 'question' },

  { nl: 'I work for a technology company.',
    en: 'Trabajo en una empresa de tecnología.',
    level: 'A2', unit: 2, stype: 'Statement',
    srule: 'I + work + for + artículo + adjetivo + noun — "work for" para el empleador' },

  { nl: 'I prefer winter to summer.',
    en: 'Me gusta más el invierno que el verano.',
    level: 'A2', unit: 3, stype: 'Statement',
    srule: 'I + prefer + noun + to + noun — comparación con "prefer ... to"' },

  { nl: 'Can you speak more slowly, please?',
    en: '¿Puedes hablar más despacio, por favor?',
    level: 'A2', unit: 3, stype: 'Question',
    srule: 'Can + you + verbo base + comparativo de adverbio — petición con "can"',
    gtopic: 'question' },

  { nl: 'When I was a child, I lived in the countryside.',
    en: 'Cuando era niño, vivía en el campo.',
    level: 'A2', unit: 6, stype: 'Compound sentence',
    srule: 'When + sujeto + was + noun, sujeto + verbo pasado — oración compuesta' },

  { nl: 'I am going to visit my parents at the weekend.',
    en: 'Voy a visitar a mis padres el fin de semana.',
    level: 'A2', unit: 5, stype: 'Statement',
    srule: 'I + am going to + verbo base — futuro "going to" para planes concretos',
    gtopic: 'tenses' },

  { nl: 'I have not finished my homework yet.',
    en: 'Todavía no he terminado mis deberes.',
    level: 'A2', unit: 6, stype: 'Negation',
    srule: 'I + have + not + participio + yet — presente perfecto negativo con "yet" al final',
    gtopic: 'negation' },

  // ── Pasado simple (Unit 6) ─────────────────────────────
  { nl: 'I went to the cinema last night.',
    en: 'Fui al cine anoche.',
    level: 'A2', unit: 6, stype: 'Statement',
    srule: 'I + went (pasado de go) + to + lugar + marcador temporal' },

  { nl: 'She bought a new dress yesterday.',
    en: 'Ella compró un vestido nuevo ayer.',
    level: 'A2', unit: 6, stype: 'Statement',
    srule: 'She + bought (pasado de buy) + artículo + adjetivo + noun + yesterday' },

  { nl: 'We ate pizza for dinner.',
    en: 'Cenamos pizza.',
    level: 'A2', unit: 6, stype: 'Statement',
    srule: 'We + ate (pasado de eat) + noun + for dinner' },

  { nl: 'Did you see the film?',
    en: '¿Viste la película?',
    level: 'A2', unit: 6, stype: 'Question',
    srule: 'Did + you + verbo base — pregunta en pasado simple con "did"',
    gtopic: 'question' },

  { nl: 'He did not come to class.',
    en: 'Él no vino a clase.',
    level: 'A2', unit: 6, stype: 'Negation',
    srule: 'He + did not + verbo base — negación en pasado simple con "did not"',
    gtopic: 'negation' },

  { nl: 'I took the bus to work.',
    en: 'Tomé el autobús para ir al trabajo.',
    level: 'A2', unit: 6, stype: 'Statement',
    srule: 'I + took (pasado de take) + artículo + noun + to + lugar' },

  { nl: 'They made a cake for the party.',
    en: 'Hicieron un pastel para la fiesta.',
    level: 'A2', unit: 6, stype: 'Statement',
    srule: 'They + made (pasado de make) + artículo + noun + for + noun' },

  { nl: 'What did you do last weekend?',
    en: '¿Qué hiciste el fin de semana pasado?',
    level: 'A2', unit: 6, stype: 'Question',
    srule: 'What + did + you + do — pregunta en pasado con "did"',
    gtopic: 'question' },

  { nl: 'I gave her a present.',
    en: 'Le di un regalo.',
    level: 'A2', unit: 6, stype: 'Statement',
    srule: 'I + gave (pasado de give) + pronombre objeto + artículo + noun' },

  { nl: 'We did not go to the beach.',
    en: 'No fuimos a la playa.',
    level: 'A2', unit: 6, stype: 'Negation',
    srule: 'We + did not + verbo base — negación en pasado simple',
    gtopic: 'negation' },

  { nl: 'I cooked dinner last night.',
    en: 'Cociné la cena anoche.',
    level: 'A2', unit: 6, stype: 'Statement',
    srule: 'I + cooked (pasado regular: cook + -ed) + noun + marcador temporal' },

  { nl: 'She walked to school yesterday.',
    en: 'Ella caminó a la escuela ayer.',
    level: 'A2', unit: 6, stype: 'Statement',
    srule: 'She + walked (pasado regular: walk + -ed) + to + lugar + yesterday' },

  { nl: 'I ate rice and chicken last night.',
    en: 'Comí arroz y pollo anoche.',
    level: 'A2', unit: 6, stype: 'Statement',
    srule: 'I + ate (pasado de eat) + food + food + time — pasado simple con comida' },

  { nl: 'We took the train yesterday morning.',
    en: 'Tomamos el tren ayer por la mañana.',
    level: 'A2', unit: 6, stype: 'Statement',
    srule: 'We + took (pasado de take) + artículo + transport + time — pasado con transporte' },

  { nl: 'Did you drink coffee this morning?',
    en: '¿Bebiste café esta mañana?',
    level: 'A2', unit: 6, stype: 'Question',
    srule: 'Did + you + drink (base) + food + time — pregunta en pasado con comida',
    gtopic: 'question' },

  { nl: 'She did not buy bread yesterday.',
    en: 'Ella no compró pan ayer.',
    level: 'A2', unit: 6, stype: 'Negation',
    srule: 'She + did not + buy (base) + food + time — negación en pasado con comida',
    gtopic: 'negation' },

  { nl: 'I went to the airport last week.',
    en: 'Fui al aeropuerto la semana pasada.',
    level: 'A2', unit: 6, stype: 'Statement',
    srule: 'I + went (pasado de go) + to + transport place + time — pasado con transporte' },

];

// ════════════════════════════════════════════════════════════
//  2. verbs
// ════════════════════════════════════════════════════════════
const verbs = [
  // modal
  ii('can',    'poder (capacidad)',   ['can','can','can','can','can','can'],             'could',  'could',   'been able to', 'have'),
  ii('could',  'podría / sabía',      ['could','could','could','could','could','could'], '—',      '—',       '—',       'have'),
  ii('must',   'deber (obligación)',   ['must','must','must','must','must','must'],       '—',      '—',       '—',       'have'),
  ii('should', 'debería (consejo)',    ['should','should','should','should','should','should'], '—','—',      '—',       'have'),
  ii('will',   'futuro / voluntad',    ['will','will','will','will','will','will'],       'would',  'would',   '—',       'have'),
  ii('would',  'condicional',          ['would','would','would','would','would','would'], '—',     '—',       '—',       'have'),
  ii('may',    'poder (permiso)',      ['may','may','may','may','may','may'],             'might',  'might',   '—',       'have'),
  ii('might',  'podría (posibilidad)', ['might','might','might','might','might','might'], '—',     '—',       '—',       'have'),
  // irregular
  ii('be',     'ser / estar',        ['am','are','is','are','are','are'],               'was',    'were',    'been',    'have'),
  ii('have',   'tener / haber',      ['have','have','has','have','have','have'],         'had',    'had',     'had',     'have'),
  ii('do',     'hacer',              ['do','do','does','do','do','do'],                  'did',    'did',     'done',    'have'),
  ii('go',     'ir',                 ['go','go','goes','go','go','go'],                  'went',   'went',    'gone',    'have'),
  ii('say',    'decir',              ['say','say','says','say','say','say'],              'said',   'said',    'said',    'have'),
  ii('get',    'obtener / llegar',   ['get','get','gets','get','get','get'],              'got',    'got',     'got',     'have'),
  ii('make',   'hacer / fabricar',   ['make','make','makes','make','make','make'],        'made',   'made',    'made',    'have'),
  ii('know',   'saber / conocer',    ['know','know','knows','know','know','know'],        'knew',   'knew',    'known',   'have'),
  ii('think',  'pensar / creer',     ['think','think','thinks','think','think','think'],  'thought','thought', 'thought', 'have'),
  ii('come',   'venir',              ['come','come','comes','come','come','come'],        'came',   'came',    'come',    'have'),
  ii('see',    'ver',                ['see','see','sees','see','see','see'],              'saw',    'saw',     'seen',    'have'),
  ii('want',   'querer',             ['want','want','wants','want','want','want'],        'wanted', 'wanted',  'wanted',  'have'),
  ii('give',   'dar',                ['give','give','gives','give','give','give'],        'gave',   'gave',    'given',   'have'),
  ii('feel',   'sentir / sentirse',  ['feel','feel','feels','feel','feel','feel'],        'felt',   'felt',    'felt',    'have'),
  ii('read',   'leer',               ['read','read','reads','read','read','read'],        'read',   'read',    'read',    'have'),
  ii('write',  'escribir',           ['write','write','writes','write','write','write'],  'wrote',  'wrote',   'written', 'have'),
  ii('speak',  'hablar',             ['speak','speak','speaks','speak','speak','speak'],  'spoke',  'spoke',   'spoken',  'have'),
  ii('take',   'tomar / llevar',     ['take','take','takes','take','take','take'],        'took',   'took',    'taken',   'have'),
  ii('buy',    'comprar',            ['buy','buy','buys','buy','buy','buy'],              'bought', 'bought',  'bought',  'have'),
  ii('eat',    'comer',              ['eat','eat','eats','eat','eat','eat'],              'ate',    'ate',     'eaten',   'have'),
  ii('drink',  'beber',              ['drink','drink','drinks','drink','drink','drink'],  'drank',  'drank',   'drunk',   'have'),
  // regular
  r('work',    'trabajar'),
  r('study',   'estudiar'),
  r('live',    'vivir'),
  r('listen',  'escuchar'),
  r('watch',   'mirar / ver'),
  r('play',    'jugar / tocar'),
  r('cook',    'cocinar'),
  r('walk',    'caminar'),
  r('travel',  'viajar'),
  r('learn',   'aprender'),
  r('help',    'ayudar'),
  r('love',    'amar / encantar'),
  r('like',    'gustar'),
  r('need',    'necesitar'),
  r('call',    'llamar'),
  r('open',    'abrir'),
  r('close',   'cerrar'),
  r('clean',   'limpiar'),
  r('wash',    'lavar'),
  r('talk',    'hablar / conversar'),
  r('use',     'usar'),
  r('start',   'empezar / comenzar'),
  r('finish',  'terminar'),
  r('wait',    'esperar'),
  r('ask',     'preguntar'),
  r('answer',  'responder'),
  r('change',  'cambiar'),
  r('dance',   'bailar'),
  r('visit',   'visitar'),
  r('arrive',  'llegar'),
  r('look',    'mirar'),
  r('turn',    'girar / encender'),
  r('show',    'mostrar'),
  // irregular (additional)
  ii('run',    'correr',              ['run','run','runs','run','run','run'],                'ran',    'ran',     'run',     'have'),
  ii('sit',    'sentarse',            ['sit','sit','sits','sit','sit','sit'],                'sat',    'sat',     'sat',     'have'),
  ii('sleep',  'dormir',              ['sleep','sleep','sleeps','sleep','sleep','sleep'],    'slept',  'slept',   'slept',   'have'),
  ii('swim',   'nadar',               ['swim','swim','swims','swim','swim','swim'],          'swam',   'swam',    'swum',    'have'),
  ii('drive',  'conducir',            ['drive','drive','drives','drive','drive','drive'],    'drove',  'drove',   'driven',  'have'),
  ii('fly',    'volar',               ['fly','fly','flies','fly','fly','fly'],               'flew',   'flew',    'flown',   'have'),
  ii('sing',   'cantar',              ['sing','sing','sings','sing','sing','sing'],          'sang',   'sang',    'sung',    'have'),
  ii('put',    'poner',               ['put','put','puts','put','put','put'],                'put',    'put',     'put',     'have'),
  ii('tell',   'decir / contar',      ['tell','tell','tells','tell','tell','tell'],          'told',   'told',    'told',    'have'),
  ii('find',   'encontrar',           ['find','find','finds','find','find','find'],          'found',  'found',   'found',   'have'),
  ii('leave',  'salir / dejar',       ['leave','leave','leaves','leave','leave','leave'],    'left',   'left',    'left',    'have'),
  ii('meet',   'conocer / encontrar', ['meet','meet','meets','meet','meet','meet'],          'met',    'met',     'met',     'have'),
  ii('send',   'enviar',              ['send','send','sends','send','send','send'],          'sent',   'sent',    'sent',    'have'),
  ii('bring',  'traer',               ['bring','bring','brings','bring','bring','bring'],    'brought','brought', 'brought', 'have'),
  ii('teach',  'enseñar',             ['teach','teach','teaches','teach','teach','teach'],   'taught', 'taught',  'taught',  'have'),
  ii('understand','entender',         ['understand','understand','understands','understand','understand','understand'], 'understood','understood','understood','have'),
  ii('forget', 'olvidar',             ['forget','forget','forgets','forget','forget','forget'],'forgot','forgot', 'forgotten','have'),
  ii('begin',  'empezar',             ['begin','begin','begins','begin','begin','begin'],    'began',  'began',   'begun',   'have'),
  ii('stand',  'estar de pie',        ['stand','stand','stands','stand','stand','stand'],    'stood',  'stood',   'stood',   'have'),
  ii('lose',   'perder',              ['lose','lose','loses','lose','lose','lose'],          'lost',   'lost',    'lost',    'have'),
  ii('win',    'ganar',               ['win','win','wins','win','win','win'],                'won',    'won',     'won',     'have'),
  ii('wear',   'llevar puesto',       ['wear','wear','wears','wear','wear','wear'],          'wore',   'wore',    'worn',    'have'),
  ii('grow',   'crecer',              ['grow','grow','grows','grow','grow','grow'],          'grew',   'grew',    'grown',   'have'),
  ii('keep',   'guardar / mantener',  ['keep','keep','keeps','keep','keep','keep'],          'kept',   'kept',    'kept',    'have'),
  ii('spend',  'gastar / pasar tiempo',['spend','spend','spends','spend','spend','spend'],  'spent',  'spent',   'spent',   'have'),
  ii('cut',    'cortar',              ['cut','cut','cuts','cut','cut','cut'],                'cut',    'cut',     'cut',     'have'),
  ii('catch',  'atrapar / coger',     ['catch','catch','catches','catch','catch','catch'],  'caught', 'caught',  'caught',  'have'),
  ii('fall',   'caer',                ['fall','fall','falls','fall','fall','fall'],          'fell',   'fell',    'fallen',  'have'),
  ii('break',  'romper',              ['break','break','breaks','break','break','break'],    'broke',  'broke',   'broken',  'have'),
  ii('choose', 'elegir',              ['choose','choose','chooses','choose','choose','choose'],'chose','chose',  'chosen',  'have'),
  ii('draw',   'dibujar',             ['draw','draw','draws','draw','draw','draw'],          'drew',   'drew',    'drawn',   'have'),
  ii('build',  'construir',           ['build','build','builds','build','build','build'],    'built',  'built',   'built',   'have'),
  ii('hear',   'oír',                 ['hear','hear','hears','hear','hear','hear'],          'heard',  'heard',   'heard',   'have'),
  ii('set',    'poner / establecer',  ['set','set','sets','set','set','set'],                'set',    'set',     'set',     'have'),
  ii('pay',    'pagar',               ['pay','pay','pays','pay','pay','pay'],                'paid',   'paid',    'paid',    'have'),
  ii('let',    'dejar / permitir',    ['let','let','lets','let','let','let'],                'let',    'let',     'let',     'have'),
  ii('hold',   'sostener / sujetar',  ['hold','hold','holds','hold','hold','hold'],          'held',   'held',    'held',    'have'),
  ii('try',    'intentar',            ['try','try','tries','try','try','try'],               'tried',  'tried',   'tried',   'have'),
];

// ════════════════════════════════════════════════════════════
//  3. vocabulary
//  nl = English word   |   en = Spanish translation
// ════════════════════════════════════════════════════════════
const vocabulary = [

  // greetings
  { nl: 'hello',          en: 'hola',                     type: 'expr.', level: 'A1', topic: 'greetings' },
  { nl: 'goodbye',        en: 'adiós',                    type: 'expr.', level: 'A1', topic: 'greetings' },
  { nl: 'please',         en: 'por favor',                type: 'expr.', level: 'A1', topic: 'greetings' },
  { nl: 'thank you',      en: 'gracias',                  type: 'expr.', level: 'A1', topic: 'greetings' },
  { nl: 'sorry',          en: 'lo siento',                type: 'expr.', level: 'A1', topic: 'greetings' },
  { nl: 'excuse me',      en: 'perdona / perdone',        type: 'expr.', level: 'A1', topic: 'greetings' },
  { nl: 'yes',            en: 'sí',                       type: 'expr.', level: 'A1', topic: 'greetings' },
  { nl: 'no',             en: 'no',                       type: 'expr.', level: 'A1', topic: 'greetings' },
  { nl: 'good morning',   en: 'buenos días',              type: 'expr.', level: 'A1', topic: 'greetings' },
  { nl: 'good afternoon', en: 'buenas tardes',            type: 'expr.', level: 'A1', topic: 'greetings' },
  { nl: 'good evening',   en: 'buenas tardes/noches',     type: 'expr.', level: 'A1', topic: 'greetings' },
  { nl: 'good night',     en: 'buenas noches',            type: 'expr.', level: 'A1', topic: 'greetings' },
  { nl: 'nice to meet you', en: 'mucho gusto / encantado', type: 'expr.', level: 'A1', topic: 'greetings' },
  { nl: 'see you later',    en: 'hasta luego',             type: 'expr.', level: 'A1', topic: 'greetings' },
  { nl: 'see you tomorrow', en: 'hasta mañana',            type: 'expr.', level: 'A1', topic: 'greetings' },
  { nl: 'how are you?',     en: '¿cómo estás?',            type: 'expr.', level: 'A1', topic: 'greetings' },
  { nl: 'I am fine',        en: 'estoy bien',              type: 'expr.', level: 'A1', topic: 'greetings' },

  // personal info — datos personales
  { nl: 'the name',         en: 'el nombre',               type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the surname',      en: 'el apellido',             type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the age',          en: 'la edad',                 type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the address',      en: 'la dirección',            type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the telephone number', en: 'el número de teléfono', type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the email',        en: 'el correo electrónico',   type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the city',         en: 'la ciudad',               type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the country',      en: 'el país',                 type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the nationality',  en: 'la nacionalidad',         type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the language',     en: 'el idioma',               type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the job',          en: 'el trabajo / la profesión', type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the student',      en: 'el/la estudiante',        type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the teacher',      en: 'el profesor / la profesora', type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the doctor',       en: 'el médico / la médica',   type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the person',       en: 'la persona',              type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the man',          en: 'el hombre',               type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the woman',        en: 'la mujer',                type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the boy',          en: 'el niño / el chico',      type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the girl',         en: 'la niña / la chica',      type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the school',       en: 'la escuela / el colegio', type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the book',         en: 'el libro',                type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the office',       en: 'la oficina',              type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the university',  en: 'la universidad',          type: 'n.', level: 'A1', topic: 'personal' },
  { nl: 'the word',        en: 'la palabra',              type: 'n.', level: 'A1', topic: 'personal' },

  // countries & nationalities — países y nacionalidades
  { nl: 'Spain',            en: 'España',                  type: 'n.', level: 'A1', topic: 'countries' },
  { nl: 'Spanish',          en: 'español/a',               type: 'adj.', level: 'A1', topic: 'countries' },
  { nl: 'Mexico',           en: 'México',                  type: 'n.', level: 'A1', topic: 'countries' },
  { nl: 'Mexican',          en: 'mexicano/a',              type: 'adj.', level: 'A1', topic: 'countries' },
  { nl: 'Colombia',         en: 'Colombia',                type: 'n.', level: 'A1', topic: 'countries' },
  { nl: 'Colombian',        en: 'colombiano/a',            type: 'adj.', level: 'A1', topic: 'countries' },
  { nl: 'Argentina',        en: 'Argentina',               type: 'n.', level: 'A1', topic: 'countries' },
  { nl: 'Argentine',        en: 'argentino/a',             type: 'adj.', level: 'A1', topic: 'countries' },
  { nl: 'Peru',             en: 'Perú',                    type: 'n.', level: 'A1', topic: 'countries' },
  { nl: 'Peruvian',         en: 'peruano/a',               type: 'adj.', level: 'A1', topic: 'countries' },
  { nl: 'Paraguay',         en: 'Paraguay',                type: 'n.', level: 'A1', topic: 'countries' },
  { nl: 'Paraguayan',       en: 'paraguayo/a',             type: 'adj.', level: 'A1', topic: 'countries' },
  { nl: 'the United States',en: 'los Estados Unidos',      type: 'n.', level: 'A1', topic: 'countries' },
  { nl: 'American',         en: 'estadounidense',          type: 'adj.', level: 'A1', topic: 'countries' },
  { nl: 'England',          en: 'Inglaterra',              type: 'n.', level: 'A1', topic: 'countries' },
  { nl: 'English',          en: 'inglés/a',                type: 'adj.', level: 'A1', topic: 'countries' },
  { nl: 'Brazil',           en: 'Brasil',                  type: 'n.', level: 'A1', topic: 'countries' },
  { nl: 'Brazilian',        en: 'brasileño/a',             type: 'adj.', level: 'A1', topic: 'countries' },

  // emotions & states — emociones y estados
  { nl: 'happy',            en: 'feliz / contento/a',      type: 'adj.', level: 'A1', topic: 'emotions' },
  { nl: 'sad',              en: 'triste',                  type: 'adj.', level: 'A1', topic: 'emotions' },
  { nl: 'tired',            en: 'cansado/a',               type: 'adj.', level: 'A1', topic: 'emotions' },
  { nl: 'hungry',           en: 'hambriento/a (tener hambre)', type: 'adj.', level: 'A1', topic: 'emotions' },
  { nl: 'thirsty',          en: 'sediento/a (tener sed)',  type: 'adj.', level: 'A1', topic: 'emotions' },
  { nl: 'well',             en: 'bien',                    type: 'adv.', level: 'A1', topic: 'emotions' },
  { nl: 'sick',             en: 'enfermo/a',               type: 'adj.', level: 'A1', topic: 'emotions' },
  { nl: 'angry',            en: 'enfadado/a',              type: 'adj.', level: 'A1', topic: 'emotions' },
  { nl: 'nervous',          en: 'nervioso/a',              type: 'adj.', level: 'A1', topic: 'emotions' },
  { nl: 'busy',             en: 'ocupado/a',               type: 'adj.', level: 'A1', topic: 'emotions' },

  // family
  { nl: 'the mother',         en: 'la madre',                 type: 'n.', level: 'A1', topic: 'family' },
  { nl: 'the father',         en: 'el padre',                 type: 'n.', level: 'A1', topic: 'family' },
  { nl: 'the sister',         en: 'la hermana',               type: 'n.', level: 'A1', topic: 'family' },
  { nl: 'the brother',        en: 'el hermano',               type: 'n.', level: 'A1', topic: 'family' },
  { nl: 'the son',            en: 'el hijo',                  type: 'n.', level: 'A1', topic: 'family' },
  { nl: 'the daughter',       en: 'la hija',                  type: 'n.', level: 'A1', topic: 'family' },
  { nl: 'the grandmother',    en: 'la abuela',                type: 'n.', level: 'A1', topic: 'family' },
  { nl: 'the grandfather',    en: 'el abuelo',                type: 'n.', level: 'A1', topic: 'family' },
  { nl: 'the husband',        en: 'el marido',                type: 'n.', level: 'A1', topic: 'family' },
  { nl: 'the wife',           en: 'la mujer / la esposa',     type: 'n.', level: 'A1', topic: 'family' },
  { nl: 'the friend',         en: 'el amigo / la amiga',      type: 'n.', level: 'A1', topic: 'family' },
  { nl: 'the baby',           en: 'el bebé',                  type: 'n.', level: 'A1', topic: 'family' },
  { nl: 'the child',          en: 'el niño / la niña',        type: 'n.', level: 'A1', topic: 'family' },
  { nl: 'the parents',        en: 'los padres',               type: 'n.', level: 'A1', topic: 'family' },
  { nl: 'the family',         en: 'la familia',               type: 'n.', level: 'A1', topic: 'family' },

  // food & drink
  { nl: 'the water',          en: 'el agua',                  type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the coffee',         en: 'el café',                  type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the tea',            en: 'el té',                    type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the bread',          en: 'el pan',                   type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the rice',           en: 'el arroz',                 type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the chicken',        en: 'el pollo',                 type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the fish',           en: 'el pescado',               type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the apple',          en: 'la manzana',               type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the orange',         en: 'la naranja',               type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the milk',           en: 'la leche',                 type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the egg',            en: 'el huevo',                 type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the vegetable',      en: 'la verdura',               type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the fruit',          en: 'la fruta',                 type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the sugar',          en: 'el azúcar',                type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the salt',           en: 'la sal',                   type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the meat',           en: 'la carne',                 type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the breakfast',      en: 'el desayuno',              type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the lunch',          en: 'el almuerzo / la comida',  type: 'n.', level: 'A1', topic: 'food' },
  { nl: 'the dinner',         en: 'la cena',                  type: 'n.', level: 'A1', topic: 'food' },

  // clothing
  { nl: 'the shirt',          en: 'la camiseta',              type: 'n.', level: 'A1', topic: 'clothing' },
  { nl: 'the trousers',       en: 'los pantalones',           type: 'n.', level: 'A1', topic: 'clothing' },
  { nl: 'the dress',          en: 'el vestido',               type: 'n.', level: 'A1', topic: 'clothing' },
  { nl: 'the shoes',          en: 'los zapatos',              type: 'n.', level: 'A1', topic: 'clothing' },
  { nl: 'the jacket',         en: 'la chaqueta / el abrigo',  type: 'n.', level: 'A1', topic: 'clothing' },
  { nl: 'the hat',            en: 'el sombrero',              type: 'n.', level: 'A1', topic: 'clothing' },
  { nl: 'the socks',          en: 'los calcetines',           type: 'n.', level: 'A1', topic: 'clothing' },
  { nl: 'the bag',            en: 'el bolso',                 type: 'n.', level: 'A1', topic: 'clothing' },
  { nl: 'the jeans',          en: 'los vaqueros',             type: 'n.', level: 'A1', topic: 'clothing' },
  { nl: 'the glasses',        en: 'las gafas',                type: 'n.', level: 'A1', topic: 'clothing' },
  { nl: 'the clothes',       en: 'la ropa',                  type: 'n.', level: 'A1', topic: 'clothing' },

  // colours
  { nl: 'red',            en: 'rojo/a',                   type: 'adj.', level: 'A1', topic: 'colours' },
  { nl: 'blue',           en: 'azul',                     type: 'adj.', level: 'A1', topic: 'colours' },
  { nl: 'green',          en: 'verde',                    type: 'adj.', level: 'A1', topic: 'colours' },
  { nl: 'yellow',         en: 'amarillo/a',               type: 'adj.', level: 'A1', topic: 'colours' },
  { nl: 'black',          en: 'negro/a',                  type: 'adj.', level: 'A1', topic: 'colours' },
  { nl: 'white',          en: 'blanco/a',                 type: 'adj.', level: 'A1', topic: 'colours' },
  { nl: 'orange',         en: 'naranja',                  type: 'adj.', level: 'A1', topic: 'colours' },
  { nl: 'purple',         en: 'morado/a',                 type: 'adj.', level: 'A1', topic: 'colours' },
  { nl: 'pink',           en: 'rosa',                     type: 'adj.', level: 'A1', topic: 'colours' },
  { nl: 'brown',          en: 'marrón',                   type: 'adj.', level: 'A1', topic: 'colours' },
  { nl: 'grey',           en: 'gris',                     type: 'adj.', level: 'A1', topic: 'colours' },
  { nl: 'the colour',    en: 'el color',                 type: 'n.', level: 'A1', topic: 'colours' },

  // numbers
  { nl: 'one',            en: 'uno',                      type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'two',            en: 'dos',                      type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'three',          en: 'tres',                     type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'four',           en: 'cuatro',                   type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'five',           en: 'cinco',                    type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'six',            en: 'seis',                     type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'seven',          en: 'siete',                    type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'eight',          en: 'ocho',                     type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'nine',           en: 'nueve',                    type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'ten',            en: 'diez',                     type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'eleven',         en: 'once',                     type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'twelve',         en: 'doce',                     type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'thirteen',       en: 'trece',                    type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'fourteen',       en: 'catorce',                  type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'fifteen',        en: 'quince',                   type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'sixteen',        en: 'dieciséis',                type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'seventeen',      en: 'diecisiete',               type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'eighteen',       en: 'dieciocho',                type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'nineteen',       en: 'diecinueve',               type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'twenty',         en: 'veinte',                   type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'fifty',          en: 'cincuenta',                type: 'n.', level: 'A1', topic: 'numbers' },
  { nl: 'one hundred',    en: 'cien',                     type: 'n.', level: 'A1', topic: 'numbers' },

  // time
  { nl: 'today',              en: 'hoy',                      type: 'adv.', level: 'A1', topic: 'time' },
  { nl: 'tomorrow',           en: 'mañana',                   type: 'adv.', level: 'A1', topic: 'time' },
  { nl: 'yesterday',          en: 'ayer',                     type: 'adv.', level: 'A1', topic: 'time' },
  { nl: 'the morning',        en: 'la mañana',                type: 'n.', level: 'A1', topic: 'time' },
  { nl: 'the afternoon',      en: 'la tarde',                 type: 'n.', level: 'A1', topic: 'time' },
  { nl: 'the evening',        en: 'la tarde / noche',         type: 'n.', level: 'A1', topic: 'time' },
  { nl: 'the night',          en: 'la noche',                 type: 'n.', level: 'A1', topic: 'time' },
  { nl: 'the week',           en: 'la semana',                type: 'n.', level: 'A1', topic: 'time' },
  { nl: 'the month',          en: 'el mes',                   type: 'n.', level: 'A1', topic: 'time' },
  { nl: 'the year',           en: 'el año',                   type: 'n.', level: 'A1', topic: 'time' },
  { nl: 'Monday',             en: 'el lunes',                 type: 'n.', level: 'A1', topic: 'time' },
  { nl: 'Tuesday',            en: 'el martes',                type: 'n.', level: 'A1', topic: 'time' },
  { nl: 'Wednesday',          en: 'el miércoles',             type: 'n.', level: 'A1', topic: 'time' },
  { nl: 'Thursday',           en: 'el jueves',                type: 'n.', level: 'A1', topic: 'time' },
  { nl: 'Friday',             en: 'el viernes',               type: 'n.', level: 'A1', topic: 'time' },
  { nl: 'Saturday',           en: 'el sábado',                type: 'n.', level: 'A1', topic: 'time' },
  { nl: 'Sunday',             en: 'el domingo',               type: 'n.', level: 'A1', topic: 'time' },
  { nl: 'the day',            en: 'el día',                   type: 'n.', level: 'A1', topic: 'time' },
  { nl: 'the hour',           en: 'la hora',                  type: 'n.', level: 'A1', topic: 'time' },

  // transport
  { nl: 'the car',            en: 'el coche',                 type: 'n.', level: 'A1', topic: 'transport' },
  { nl: 'the bus',            en: 'el autobús',               type: 'n.', level: 'A1', topic: 'transport' },
  { nl: 'the train',          en: 'el tren',                  type: 'n.', level: 'A1', topic: 'transport' },
  { nl: 'the plane',          en: 'el avión',                 type: 'n.', level: 'A1', topic: 'transport' },
  { nl: 'the bicycle',        en: 'la bicicleta',             type: 'n.', level: 'A1', topic: 'transport' },
  { nl: 'the taxi',           en: 'el taxi',                  type: 'n.', level: 'A1', topic: 'transport' },
  { nl: 'the station',        en: 'la estación',              type: 'n.', level: 'A1', topic: 'transport' },
  { nl: 'the airport',        en: 'el aeropuerto',            type: 'n.', level: 'A1', topic: 'transport' },
  { nl: 'the road',           en: 'la carretera',             type: 'n.', level: 'A1', topic: 'transport' },
  { nl: 'the ticket',         en: 'el billete',               type: 'n.', level: 'A1', topic: 'transport' },

  // home
  { nl: 'the house',          en: 'la casa',                  type: 'n.', level: 'A1', topic: 'home' },
  { nl: 'the room',           en: 'la habitación',            type: 'n.', level: 'A1', topic: 'home' },
  { nl: 'the bedroom',        en: 'el dormitorio',            type: 'n.', level: 'A1', topic: 'home' },
  { nl: 'the kitchen',        en: 'la cocina',                type: 'n.', level: 'A1', topic: 'home' },
  { nl: 'the bathroom',       en: 'el baño',                  type: 'n.', level: 'A1', topic: 'home' },
  { nl: 'the garden',         en: 'el jardín',                type: 'n.', level: 'A1', topic: 'home' },
  { nl: 'the door',           en: 'la puerta',                type: 'n.', level: 'A1', topic: 'home' },
  { nl: 'the window',         en: 'la ventana',               type: 'n.', level: 'A1', topic: 'home' },
  { nl: 'the table',          en: 'la mesa',                  type: 'n.', level: 'A1', topic: 'home' },
  { nl: 'the chair',          en: 'la silla',                 type: 'n.', level: 'A1', topic: 'home' },
  { nl: 'the bed',            en: 'la cama',                  type: 'n.', level: 'A1', topic: 'home' },
  { nl: 'the apartment',     en: 'el apartamento / el piso', type: 'n.', level: 'A1', topic: 'home' },
  { nl: 'the supermarket',   en: 'el supermercado',          type: 'n.', level: 'A1', topic: 'home' },
  { nl: 'the fridge',        en: 'la nevera',                type: 'n.', level: 'A1', topic: 'home' },
  { nl: 'home',              en: 'el hogar / en casa',       type: 'n.', level: 'A1', topic: 'home' },

  // body
  { nl: 'the head',           en: 'la cabeza',                type: 'n.', level: 'A1', topic: 'body' },
  { nl: 'the eye',            en: 'el ojo',                   type: 'n.', level: 'A1', topic: 'body' },
  { nl: 'the nose',           en: 'la nariz',                 type: 'n.', level: 'A1', topic: 'body' },
  { nl: 'the mouth',          en: 'la boca',                  type: 'n.', level: 'A1', topic: 'body' },
  { nl: 'the hand',           en: 'la mano',                  type: 'n.', level: 'A1', topic: 'body' },
  { nl: 'the arm',            en: 'el brazo',                 type: 'n.', level: 'A1', topic: 'body' },
  { nl: 'the leg',            en: 'la pierna',                type: 'n.', level: 'A1', topic: 'body' },
  { nl: 'the foot',           en: 'el pie',                   type: 'n.', level: 'A1', topic: 'body' },
  { nl: 'the ear',            en: 'la oreja',                 type: 'n.', level: 'A1', topic: 'body' },
  { nl: 'the hair',           en: 'el pelo / el cabello',     type: 'n.', level: 'A1', topic: 'body' },
  { nl: 'the face',           en: 'la cara',                  type: 'n.', level: 'A1', topic: 'body' },

  // adjectives
  { nl: 'big',            en: 'grande',                   type: 'adj.', level: 'A1', topic: 'adjective' },
  { nl: 'small',          en: 'pequeño/a',                type: 'adj.', level: 'A1', topic: 'adjective' },
  { nl: 'new',            en: 'nuevo/a',                  type: 'adj.', level: 'A1', topic: 'adjective' },
  { nl: 'old',            en: 'viejo/a',                  type: 'adj.', level: 'A1', topic: 'adjective' },
  { nl: 'good',           en: 'bueno/a',                  type: 'adj.', level: 'A1', topic: 'adjective' },
  { nl: 'bad',            en: 'malo/a',                   type: 'adj.', level: 'A1', topic: 'adjective' },
  { nl: 'hot',            en: 'caliente',                 type: 'adj.', level: 'A1', topic: 'adjective' },
  { nl: 'cold',           en: 'frío/a',                   type: 'adj.', level: 'A1', topic: 'adjective' },
  { nl: 'fast',           en: 'rápido/a',                 type: 'adj.', level: 'A1', topic: 'adjective' },
  { nl: 'slow',           en: 'lento/a',                  type: 'adj.', level: 'A1', topic: 'adjective' },
  { nl: 'beautiful',      en: 'bonito/a / hermoso/a',     type: 'adj.', level: 'A1', topic: 'adjective' },
  { nl: 'easy',           en: 'fácil',                    type: 'adj.', level: 'A1', topic: 'adjective' },
  { nl: 'difficult',      en: 'difícil',                  type: 'adj.', level: 'A1', topic: 'adjective' },
  { nl: 'cheap',          en: 'barato/a',                 type: 'adj.', level: 'A1', topic: 'adjective' },
  { nl: 'expensive',      en: 'caro/a',                   type: 'adj.', level: 'A1', topic: 'adjective' },

];

// ════════════════════════════════════════════════════════════
//  4. dehetWords  →  A/An practice for English
//  word = English word   |   en = Spanish translation
// ════════════════════════════════════════════════════════════
const dehetWords = [
  // "an" — vowel sounds
  { word: 'apple',         article: 'an', level: 'A1', en: 'manzana',
    reason: 'Usa "an" antes de sonidos vocálicos (a, e, i, o, u).',
    reasonEn: 'Use "an" before vowel sounds (a, e, i, o, u).' },
  { word: 'elephant',      article: 'an', level: 'A1', en: 'elefante',
    reason: 'Comienza con sonido vocálico /ɛ/.',
    reasonEn: 'Starts with vowel sound /ɛ/.' },
  { word: 'ice cream',     article: 'an', level: 'A1', en: 'helado',
    reason: 'Comienza con sonido vocálico /aɪ/.',
    reasonEn: 'Starts with vowel sound /aɪ/.' },
  { word: 'orange',        article: 'an', level: 'A1', en: 'naranja',
    reason: 'Comienza con sonido vocálico /ɒ/.',
    reasonEn: 'Starts with vowel sound /ɒ/.' },
  { word: 'umbrella',      article: 'an', level: 'A1', en: 'paraguas',
    reason: 'Comienza con sonido vocálico /ʌ/.',
    reasonEn: 'Starts with vowel sound /ʌ/.' },
  { word: 'hour',          article: 'an', level: 'A1', en: 'hora',
    reason: 'La "h" es muda; el sonido inicial es vocálico /aʊ/.',
    reasonEn: 'The "h" is silent; the first sound is the vowel /aʊ/.' },
  { word: 'honest person', article: 'an', level: 'A1', en: 'persona honesta',
    reason: 'La "h" es muda en "honest"; el sonido inicial es /ɒ/.',
    reasonEn: 'The "h" in "honest" is silent; first sound is /ɒ/.' },
  { word: 'egg',           article: 'an', level: 'A1', en: 'huevo',
    reason: 'Comienza con sonido vocálico /ɛ/.',
    reasonEn: 'Starts with vowel sound /ɛ/.' },
  { word: 'animal',        article: 'an', level: 'A1', en: 'animal',
    reason: 'Comienza con sonido vocálico /æ/.',
    reasonEn: 'Starts with vowel sound /æ/.' },
  { word: 'airport',       article: 'an', level: 'A1', en: 'aeropuerto',
    reason: 'Comienza con sonido vocálico /ɛ/.',
    reasonEn: 'Starts with vowel sound /ɛ/.' },
  { word: 'office',        article: 'an', level: 'A1', en: 'oficina',
    reason: 'Comienza con sonido vocálico /ɒ/.',
    reasonEn: 'Starts with vowel sound /ɒ/.' },
  { word: 'email',         article: 'an', level: 'A1', en: 'correo electrónico',
    reason: 'Comienza con sonido vocálico /iː/.',
    reasonEn: 'Starts with vowel sound /iː/.' },
  { word: 'idea',          article: 'an', level: 'A1', en: 'idea',
    reason: 'Comienza con sonido vocálico /aɪ/.',
    reasonEn: 'Starts with vowel sound /aɪ/.' },
  { word: 'uncle',         article: 'an', level: 'A1', en: 'tío',
    reason: 'Comienza con sonido vocálico /ʌ/.',
    reasonEn: 'Starts with vowel sound /ʌ/.' },
  { word: 'ocean',         article: 'an', level: 'A1', en: 'océano',
    reason: 'Comienza con sonido vocálico /əʊ/.',
    reasonEn: 'Starts with vowel sound /əʊ/.' },
  { word: 'island',        article: 'an', level: 'A1', en: 'isla',
    reason: 'Comienza con sonido vocálico /aɪ/ (la "s" no se pronuncia).',
    reasonEn: 'Starts with vowel sound /aɪ/ (the "s" is silent).' },
  { word: 'actor',         article: 'an', level: 'A1', en: 'actor',
    reason: 'Comienza con sonido vocálico /æ/.',
    reasonEn: 'Starts with vowel sound /æ/.' },
  // "a" — consonant sounds
  { word: 'book',          article: 'a', level: 'A1', en: 'libro',
    reason: 'Comienza con sonido consonántico /b/; se usa "a".',
    reasonEn: 'Starts with consonant sound /b/; use "a".' },
  { word: 'car',           article: 'a', level: 'A1', en: 'coche',
    reason: 'Comienza con sonido consonántico /k/.',
    reasonEn: 'Starts with consonant sound /k/.' },
  { word: 'dog',           article: 'a', level: 'A1', en: 'perro',
    reason: 'Comienza con sonido consonántico /d/.',
    reasonEn: 'Starts with consonant sound /d/.' },
  { word: 'house',         article: 'a', level: 'A1', en: 'casa',
    reason: 'La "h" se pronuncia en "house"; sonido inicial consonántico /h/.',
    reasonEn: 'The "h" is pronounced in "house"; consonant sound /h/.' },
  { word: 'table',         article: 'a', level: 'A1', en: 'mesa',
    reason: 'Comienza con sonido consonántico /t/.',
    reasonEn: 'Starts with consonant sound /t/.' },
  { word: 'university',    article: 'a', level: 'A1', en: 'universidad',
    reason: '"University" empieza con sonido /juː/ (consonántico), no vocálico.',
    reasonEn: '"University" starts with /juː/ sound (like "you"), not a vowel.' },
  { word: 'European city', article: 'a', level: 'A1', en: 'ciudad europea',
    reason: '"European" empieza con sonido /jʊ/ (consonántico).',
    reasonEn: '"European" starts with /jʊ/ sound (consonant).' },
  { word: 'year',          article: 'a', level: 'A1', en: 'año',
    reason: '"Year" empieza con sonido /j/ (consonántico).',
    reasonEn: '"Year" starts with /j/ sound (consonant).' },
  { word: 'unit',          article: 'a', level: 'A1', en: 'unidad',
    reason: '"Unit" empieza con sonido /juː/ (consonántico).',
    reasonEn: '"Unit" starts with /juː/ sound (consonant).' },
  { word: 'one-way street',article: 'a', level: 'A1', en: 'calle de sentido único',
    reason: '"One" se pronuncia /wʌn/; empieza con sonido consonántico /w/.',
    reasonEn: '"One" is pronounced /wʌn/; starts with consonant sound /w/.' },
  { word: 'cat',           article: 'a', level: 'A1', en: 'gato',
    reason: 'Comienza con sonido consonántico /k/.',
    reasonEn: 'Starts with consonant sound /k/.' },
  { word: 'school',        article: 'a', level: 'A1', en: 'escuela',
    reason: 'Comienza con sonido consonántico /sk/.',
    reasonEn: 'Starts with consonant sound /sk/.' },
  { word: 'teacher',       article: 'a', level: 'A1', en: 'profesor/a',
    reason: 'Comienza con sonido consonántico /t/.',
    reasonEn: 'Starts with consonant sound /t/.' },
  { word: 'doctor',        article: 'a', level: 'A1', en: 'médico/a',
    reason: 'Comienza con sonido consonántico /d/.',
    reasonEn: 'Starts with consonant sound /d/.' },
  { word: 'friend',        article: 'a', level: 'A1', en: 'amigo/a',
    reason: 'Comienza con sonido consonántico /f/.',
    reasonEn: 'Starts with consonant sound /f/.' },
  { word: 'city',          article: 'a', level: 'A1', en: 'ciudad',
    reason: 'Comienza con sonido consonántico /s/.',
    reasonEn: 'Starts with consonant sound /s/.' },
  { word: 'boy',           article: 'a', level: 'A1', en: 'niño / chico',
    reason: 'Comienza con sonido consonántico /b/.',
    reasonEn: 'Starts with consonant sound /b/.' },
  { word: 'girl',          article: 'a', level: 'A1', en: 'niña / chica',
    reason: 'Comienza con sonido consonántico /ɡ/.',
    reasonEn: 'Starts with consonant sound /ɡ/.' },
];

// ── expose ───────────────────────────────────────────────────
if (typeof module !== 'undefined') {
  module.exports = { defaultSentences, verbs, vocabulary, dehetWords };
}
